analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    uri_has_not_been_generated: ignore
#    todo: ignore
#    missing_return: error
#    dead_code: info
#
#linter:
#  rules:
#    - avoid_empty_else