name: 'webgl_application'
version: 0.0.1
description: Building a webgl application
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=2.0.0-dev.30.0 <2.0.0'

dependencies:
  reflectable:
    git: https://github.com/dart-lang/reflectable.git
  angular: ^5.0.0-alpha+7
  angular_components: ^0.9.0-alpha+7
  angular_forms: ^1.0.1-alpha+7
  angular_router: ^2.0.0-alpha+7
  angular_test: ^2.0.0-alpha+5
  webgl:
    path: ../webgl
  vector_math: any
  logging: "^0.11.3+1"
  stack_trace: "^1.8.2"
  node_engine:
    path: D:\JEROME\dev\repositories\node_engine

dev_dependencies:
  build_runner: ^0.7.11+1
  build_test: ^0.10.1
  build_web_compilers: ^0.3.1
  test: '>=0.12.0 <0.13.0'

dependency_overrides:
  analyzer: ^0.31.0-alpha.1
