name: 'webgl_application'
version: 0.0.1
description: Building a webgl application
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=2.0.0-dev.58.0 <=2.0.0'

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  reflectable:
    git: https://github.com/dart-lang/reflectable.git
  webgl:
    path: ../webgl
  vector_math: any
  logging: "^0.11.3+1"
  stack_trace: "^1.8.2"
  node_engine:
    path: D:\JEROME\dev\repositories\node_engine

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  build_test: ^0.10.2
  test: ^1.3.0
  angular_test: ^2.0.0

# Since IntelliJ 2018.2.1 html page can be launch directly in browser.

# Previous version need to use the following way :
# https://webdev.dartlang.org/tools/webdev#command-build
# https://webdev.dartlang.org/dart-2

# 1 - launch reflectable builder if needed. Before launching in, be sure to delete previous generated reflectable files.
# >> dart tool/builder.dart web/*.dart
# >> dart tool/builder.dart web/webgl/editor/*.dart

# va générer main.reflectable.dart
#
# 2 - serve
# >> webdev serve
# va générer main.reflectable.dart
# va render disponible http://localhost:8080
#
# 3 - build
# build > webdev build
# ||
# pubspec.yaml > pub.bat global run webdev build --output=web:build
# va générer main.reflectable.dart
# va générer le dossier build