name: 'webgl_application'
version: 0.0.1
description: Building a webgl application
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=2.0.0-dev.58.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha
  angular_forms: ^2.0.0-alpha
  angular_router: ^2.0.0-alpha
  reflectable:
    git: https://github.com/dart-lang/reflectable.git
  webgl:
    path: ../webgl
  vector_math: any
  logging: "^0.11.3+1"
  stack_trace: "^1.8.2"
  node_engine:
    path: D:\JEROME\dev\repositories\node_engine

dev_dependencies:
  build_runner: ^0.8.8
  build_web_compilers: ^0.4.0
  test: ^0.12.35
  angular_test: ^2.0.0-alpha

# 1 - launch reflectable builder if needed
# >> dart tool/builder.dart web/*.dart
# va générer main.reflectable.dart

# 2 - serve
# >> webdev serve
# va générer main.template.reflectable.dart
# va render disponible http://localhost:8080

