name: 'webgl'
version: 0.0.5
description: Building a webgl API
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  resource: ^2.1.6
  vector_math: ^2.0.8
  logging: ^0.11.3+2
  stack_trace: ^1.9.3
  reflectable: ^2.2.0
  gltf:
    path: ../../gltf
  #    git: git://github.com/KhronosGroup/glTF-Validator.git

dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers: ^2.7.1
  build_test: ^0.10.10
  test: ^1.9.4

# Since IntelliJ 2018.2.1 html page can be launch directly in browser.

# cleaner les build
# pub run build_runner clean
# pub run build_runner daemon > to check if daemon is launching correctly

# Previous version need to use the following way :
# https://webdev.dartlang.org/tools/webdev#command-build
# https://webdev.dartlang.org/dart-2

# 1 - launch reflectable builder if needed.
#  ! Before launching it, be sure to delete previous generated reflectable files.
# >> générer main.reflectable.dart :
# dart tool/builder.dart web/**/*.dart
#
#
# 2 - serve
# générer main.reflectable.dart et construire le dossier .dart_tool/build
# render disponible http://localhost:8080
# >> webdev serve
# >> pub.bat global run webdev serve web:8080
#
#
# 3 - build
# build > webdev build
# ||
# générer main.reflectable.dart
# générer le dossier build
# pubspec.yaml > pub.bat global run webdev build


## !! si blocage au lancement, ne pas hésiter à supprimer tous les fichier *.reflectable.dart du dossier webgl puis relancer