name: 'webgl'
version: 0.0.5
description: Building a webgl API
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=2.0.0-dev.68.0 <=2.1.0'

dependencies:
  resource: ^2.1.5
  vector_math: ^2.0.8
  gltf:
    path: ../../gltf
#    git: git://github.com/KhronosGroup/glTF-Validator.git
  logging: ^0.11.3+1
  stack_trace: ^1.9.2
  reflectable: ^2.0.8+1

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers:
  build_test: ^0.10.3
  test: ^1.3.0

# Since IntelliJ 2018.2.1 html page can be launch directly in browser.

# Previous version need to use the following way :
# https://webdev.dartlang.org/tools/webdev#command-build
# https://webdev.dartlang.org/dart-2

# 1 - launch reflectable builder if needed.
#  ! Before launching it, be sure to delete previous generated reflectable files.
# >> générer main.reflectable.dart :
# dart tool/builder.dart web/**/*.dart
#
#
# 2 - serve
# générer main.reflectable.dart
# render disponible http://localhost:8080
# >> webdev serve --delete-conflicting-outputs
# >> pub.bat global run webdev serve web:57155
#
#
# 3 - build
# build > webdev build
# ||
# générer main.reflectable.dart
# générer le dossier build
# pubspec.yaml > pub.bat global run webdev build


## !! si blocage au lancement, ne pas hésiter à supprimer tous les fichier *.reflectable.dart du dossier webgl puis relancer