name: 'webgl_projects'
version: 0.0.1
description: Building a webgl projects
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  webgl:
    path: ../webgl
  resource: "^2.1.2"

dev_dependencies:
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]
- dart_to_js_script_rewriter