name: 'webgl_projects'
version: 0.0.1
description: Building a webgl projects
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=2.0.0-dev.8.0 <2.0.0'

dependencies:
  webgl:
    path: ../webgl
  webgl_application:
    path: ../webgl_application
  resource: "^2.1.2"
  browser: "^0.10.0+2"

dev_dependencies:
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions: [--trust-primitives, --trust-type-annotations]

web:
  compiler:
    debug: dartdevc