name: 'webgl_projects'
version: 0.0.1
description: Building a webgl Project
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=2.0.0-dev.58.0 <2.0.0'

dependencies:
  resource: "^2.1.4"
  webgl:
    path: ../webgl
#  webgl_application:
#    path: ../webgl_application

dev_dependencies:
  build_runner: ^0.8.8
  build_web_compilers: ^0.4.0
  build_test: ^0.10.2
  test: "^0.12.38"

# https://webdev-dartlang-org-dev.firebaseapp.com/tools/webdev#build