name: 'webExperiment'
version: 0.0.1
description: web experiment
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=2.0.0-dev.8.0 <2.0.0'

dependencies:
  test:

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- test/pub_serve:
    $include: web/
- dart_to_js_script_rewriter
- $dart2js:
    minify: true
    checked: true
    commandLineOptions: [--trust-primitives, --trust-type-annotations, --enable-experimental-mirrors]

web:
  compiler:
    debug: dartdevc