name: 'ini_editor'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  dart_to_js_script_rewriter: '^0.1.0'
  analyzer: "^0.27.1+2"
  path: "^1.3.6"
  ini: any
