name: 'test_webgl'

version: 0.0.5
description: Building a webgl API
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=2.0.0-dev.15.0 <2.0.0'

dependencies:
  vector_math: ^2.0.5
  test: ^0.12.24+8
  gltf:
    git: git://github.com/KhronosGroup/glTF-Validator.git
  datgui: "^0.2.0+1"
  logging: "^0.11.3+1"
  stack_trace: "^1.8.2"

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- test/pub_serve:
    $include: web/
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions: [--trust-primitives, --trust-type-annotations, --enable-experimental-mirrors]

web:
  compiler:
    debug: dartdevc
