name: 'webgl'
version: 0.0.5
description: Building a webgl application
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: ^2.2.0
  vector_math: any
  test:
  gltf:
    path: ../gltf
  datgui: "^0.2.0+1"

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- test/pub_serve:
    $include: web/
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/index.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]
- dart_to_js_script_rewriter
