name: 'webgl'
version: 0.0.5
description: Building a webgl API
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=2.0.0-dev.68.0 <=2.0.0'

dependencies:
  resource: ^2.1.4
  vector_math: ^2.0.5
  gltf:
    path: ../gltf
#    git: git://github.com/KhronosGroup/glTF-Validator.git
  logging: ^0.11.3+1
  stack_trace: ^1.9.2
  reflectable:
      git: https://github.com/dart-lang/reflectable.git

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  build_test: ^0.10.2
  test: ^1.3.0

# Since IntelliJ 2018.2.1 html page can be launch directly in browser.

# Previous version need to use the following way :
# https://webdev.dartlang.org/tools/webdev#command-build
#
# 1 - launch reflectable builder if needed. Before launching in, be sure to delete previous generated reflectable files.
# >> dart tool/builder.dart web/*.dart
# va générer main.reflectable.dart
#
# 2 - serve
# >> webdev serve
# va générer main.template.reflectable.dart
# va render disponible :
#  Serving `web` on http://localhost:8080
#  Serving `test` on http://localhost:8081
