name: 'webgl'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  stagexl: "^0.13.0"
  vector_math: any
  gl_enums: "^0.0.1"
  logging: "^0.11.2"
  js: ^0.6.0
  func: any
  datgui: any
  #dart_to_js_script_rewriter: '^0.1.0'
#transformers:
#- dart_to_js_script_rewriter