name: 'webgl'
version: 0.0.5
description: Building a webgl API
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=2.0.0-dev.68.0 <=2.1.0'

dependencies:
  resource: ^2.1.5
  vector_math: ^2.0.8
  gltf:
    path: ../gltf
#    git: git://github.com/KhronosGroup/glTF-Validator.git
  logging: ^0.11.3+1
  stack_trace: ^1.9.2
  reflectable: ^2.0.8+1

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0
  build_test: ^0.10.3
  test: ^1.3.0

# Since IntelliJ 2018.2.1 html page can be launch directly in browser.

# Previous version need to use the following way :
# https://webdev.dartlang.org/tools/webdev#command-build
# https://webdev.dartlang.org/dart-2

# 1 - launch reflectable builder if needed. Before launching in, be sure to delete previous generated reflectable files.
# >> dart tool/builder.dart web/*.dart
# va générer main.reflectable.dart
#
# 2 - serve
# >> webdev serve
# va générer main.reflectable.dart
# va render disponible http://localhost:8080
#
# 3 - build
# build > webdev build
# ||
# pubspec.yaml > pub.bat global run webdev build --output=web:build
# va générer main.reflectable.dart
# va générer le dossier build