name: 'webgl'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: ^2.0.0
  http: ^0.11.0
  stream_transformers: ^0.3.0
  stagexl: "^0.13.0"
  vector_math: any
  gl_enums: "^0.0.1"
  logging: "^0.11.2"
  js: ^0.6.0
  analyzer: "^0.27.1+2"
  func: any
  datgui: any
  anime_engine:
    git:
        url: https://github.com/jox81/anime_engine.git

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
- dart_to_js_script_rewriter