name: 'testBuild'
version: 0.0.5
description: Test Building dart application
author: jox81 <info@3d-jox.be>
homepage: https://www.3d-jox.be

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: ^2.2.0
  vector_math: any

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]